<?xml version="1.0" encoding="utf-8"?><Database Name="ShopCatalog" Class="PasswordDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=IGOR\SQLEXPRESS;Initial Catalog=ShopCatalog;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ShopCatalogConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Password" Member="Password">
    <Type Name="Password">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hash" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="salt" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="iterations" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="setDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>