<?xml version="1.0" encoding="utf-8"?><Database Name="ShopCatalog" Class="UserRoleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=IGOR\SQLEXPRESS;Initial Catalog=ShopCatalog;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ShopCatalogConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserRole" Member="UserRole">
    <Type Name="UserRole">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="rid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>